version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: dvwasql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=p@ssw0rd
          - MYSQL_DATABASE=dvwa
          - MYSQL_USER=root
          - MYSQL_PASSWORD=p@ssw0rd
        ports:
          - "8082:3306"
  website:
    container_name: dvwa-app
    build:
      context: ./
    ports:
      - 8000:80
